# Generated by Django 3.2.9 on 2021-12-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211203_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
    ]
