# Generated by Django 3.2.9 on 2022-01-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='added_by',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='passhistory',
            name='date',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='passhistory',
            name='username',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='verify',
            name='verify',
            field=models.CharField(max_length=60),
        ),
    ]
